# =========================
#   Jekyll – CritiqueResto
# =========================

title: CritiqueResto – Avis & critiques de restaurants
email: your-email@example.com
description: >-
  CritiqueResto publie des critiques honnêtes de restaurants partout dans le monde.
  Guides, avis détaillés, photos et expériences culinaires.

# Domaine canonique (sans www)
url: "https://critiqueresto.com"
baseurl: ""           # servi à la racine du domaine

# Commentaires (à ajuster si tu utilises Disqus)
disqus:
  shortname: critiqueresto   # <-- remplace par ton vrai shortname ou retire cette section

# Thème
theme: minima
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

# Collections
collections:
  upcoming:
    output: false
    permalink: /upcoming/:path/

# Performance / build
incremental: true
liquid:
  error_mode: warn
  strict_filters: true
  strict_variables: false
cache:
  enabled: true
  path: .jekyll-cache
limit_posts: 0
future: false
unpublished: false
lsi: false
profile: false

# CSS/HTML compression
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false

# Sass
sass:
  style: compressed
  sourcemap: never

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# jekyll-sitemap options (fichier auto à la racine du site)
jekyll-sitemap:
  filename: "/sitemap.xml"

# Fichiers à exclure de la build et de l'indexation
exclude:
  - admin/
  - admin/**/*
  - google*.html
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - package.json
  - package-lock.json
  - netlify.toml
  - "*.log"
