[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.4"
  BUNDLER_VERSION = "1.17.1"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: identity.netlify.com; style-src 'self' 'unsafe-inline' https: fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https: fonts.gstatic.com data:; connect-src 'self' https: identity.netlify.com; media-src 'self' https:; object-src 'none'; frame-src 'self' https: identity.netlify.com; worker-src 'self' blob:;" 