# =============================
# 🔧 Netlify configuration pour CritiqueResto.com
# =============================

[build]
  publish = "_site" # Jekyll génère le site ici
  command = "bundle install --deployment && JEKYLL_ENV=production bundle exec jekyll build --trace"

[build.environment]
  NODE_VERSION = "18"
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.1"
  BUNDLER_VERSION = "1.17.1"
  CONCURRENT_DOWNLOAD = "true"

# =============================
# 🔄 Traitement automatique (optimisations)
# =============================
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true

# =============================
# ⚙️ Cache & sécurité
# =============================

# HTML: revalidation rapide
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Assets: cache long
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# =============================
# 🧱 Build cache
# =============================
[build.cache]
  directories = [
    "vendor/bundle",
    "_site",
    ".jekyll-cache",
    "node_modules",
    ".bundle"
  ]

# =============================
# 🔀 Redirections
# =============================

# Interface admin (CMS)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Rediriger l’ancien site Netlify vers le nouveau domaine
[[redirects]]
  from = "https://appreciationrestaurantssherbrooke.netlify.app/*"
  to   = "https://www.critiqueresto.com/:splat"
  status = 301
  force = true

# =============================
# 🔍 Plugins
# =============================

# Génère un sitemap automatiquement
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "_site"
  baseUrl  = "https://www.critiqueresto.com"
  exclude  = [
    "**/admin/**",
    "google*.html"
  ]

# Audit Lighthouse (qualité du site)
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# =============================
# 🚀 Contextes
# =============================
[context.production]
  command = "JEKYLL_ENV=production bundle exec jekyll build --trace"

[context.deploy-preview]
  command = "JEKYLL_ENV=production bundle exec jekyll build --trace --drafts"
