[build]
  publish = "."
  command = "bundle install --deployment && npm install && JEKYLL_ENV=production bundle exec jekyll build --trace"

[build.environment]
  NODE_VERSION = "18"
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.1"
  BUNDLER_VERSION = "1.17.1"
  CONCURRENT_DOWNLOAD = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true

# Cache Headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Build Cache
[build.cache]
  directories = [
    "vendor/bundle",
    "_site",
    ".jekyll-cache",
    "node_modules",
    ".bundle"
  ]

# Redirects
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Build optimization
[context.production]
  command = "JEKYLL_ENV=production bundle exec jekyll build --trace"

[context.deploy-preview]
  command = "JEKYLL_ENV=production bundle exec jekyll build --trace --drafts"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 