[build]
  publish = "_site"
  command = "bundle install && bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.1"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-cacheing"

[plugins.inputs]
  paths = [
    "vendor/bundle",
    "_site",
    ".jekyll-cache"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 