backend:
  name: git-gateway
  repo: Natael21/blog-culinaire # your GitHub username and repository name, separated by a slash
  branch: master # optional, default value is "master"

media_folder: "static/images" # Le dossier où les images sont stockées
public_folder: "/images" # L'URL où les images seront accessibles

collections:
  - name: "restaurants"
    label: "Restaurants"
    folder: "_posts/restaurants"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nom du restaurant", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Note sur 5", name: "note", widget: "number", min: 0, max: 5 }
      - { label: "Style de nourriture", name: "style", widget: "select", options: ["Asiatique", "Italien", "Français", "Américain", "Autre"] }
      - { label: "Résumé", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Image principale", name: "image", widget: "image" }
      - { label: "Galerie d'images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"} }
