backend:
  name: git-gateway
  branch: master
  auth_type: oauth
  auth_endpoint: "https://${AUTH0_DOMAIN}/authorize"
  identity_url: "https://appreciationrestaurantssherbrooke.netlify.app/.netlify/identity"
  gateway_url: "https://appreciationrestaurantssherbrooke.netlify.app/.netlify/git"

auth:
  provider: auth0
  auth0_domain: "${AUTH0_DOMAIN}"
  client_id: "${AUTH0_CLIENT_ID}"

media_folder: "/images"
public_folder: "/images"

collections:
  - name: "restaurants"
    label: "Restaurants"
    folder: "_posts/restaurants"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nom du restaurant", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Note sur 5", name: "note", widget: "number", min: 0, max: 5 }
      - { label: "Style de nourriture", name: "style", widget: "select", options: ["Asiatique", "Italien", "Français", "Américain", "Autre"] }
      - { label: "Résumé", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Image principale", name: "image", widget: "image" }
      - { label: "Galerie d'images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"} }
