backend:
  name: git-gateway
  branch: master
  auth_type: oauth
  auth_endpoint: "https://${AUTH0_DOMAIN}/authorize"
  identity_url: "https://appreciationrestaurantssherbrooke.netlify.app/.netlify/identity"
  gateway_url: "https://appreciationrestaurantssherbrooke.netlify.app/.netlify/git"
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
  open_authoring: true
  use_graphql: true

publish_mode: editorial_workflow
locale: 'fr'
encoding: utf-8

auth:
  provider: auth0
  auth0_domain: "${AUTH0_DOMAIN}"
  client_id: "${AUTH0_CLIENT_ID}"

media_folder: "/images"
public_folder: "/images"

collections:
  - name: "restaurants"
    label: "Restaurants"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { 
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "restaurant"
        }
      - {
          label: "Nom du restaurant",
          name: "title",
          widget: "string",
          hint: "Nom complet du restaurant"
        }
      - {
          label: "Date de la visite",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "DD/MM/YYYY",
          time_format: false,
          hint: "Date de votre visite au restaurant"
        }
      - {
          label: "Note sur 5",
          name: "note",
          widget: "number",
          min: 1,
          max: 5,
          value_type: "int",
          hint: "Évaluez le restaurant de 1 à 5 étoiles"
        }
      - {
          label: "Adresse",
          name: "address",
          widget: "string",
          hint: "Adresse complète du restaurant"
        }
      - {
          label: "Style de cuisine",
          name: "style",
          widget: "select",
          options: [
            "Asiatique",
            "Italien",
            "Mexicain",
            "Bistro",
            "Américain",
            "Libano-Marocain",
            "Iranien",
            "Vietnamien",
            "Indien",
            "Café-Bistro",
            "Microbrasserie",
            "Pub",
            "Français",
            "Fusion",
            "Méditerranéen",
            "Fast-food",
            "Végétarien/Vegan",
            "Fruits de mer",
            "Autre"
          ],
          hint: "Sélectionnez le style principal de cuisine"
        }
      - {
          label: "Fourchette de prix",
          name: "price",
          widget: "select",
          options: [
            { label: "Budget ($)", value: "budget" },
            { label: "Moyen ($$)", value: "medium" },
            { label: "Luxe ($$$)", value: "expensive" }
          ],
          hint: "Sélectionnez la gamme de prix du restaurant"
        }
      - {
          label: "Description courte",
          name: "description",
          widget: "text",
          hint: "Une brève description du restaurant (max 150 caractères)",
          pattern: ['.{0,150}', "Maximum 150 caractères"]
        }
      - {
          label: "Image principale",
          name: "image",
          widget: "image",
          hint: "Image principale qui apparaîtra dans la liste et en haut de l'article",
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - {
          label: "Galerie d'images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: {
            label: "Image",
            name: "image",
            widget: "image"
          },
          hint: "Ajoutez des images supplémentaires pour la galerie (optionnel)",
          required: false
        }
      - {
          label: "Contenu de l'article",
          name: "body",
          widget: "markdown",
          hint: "Rédigez vos impressions sur le restaurant",
          default: "**Nataël** :\n\n\n\n**Nicolas** :\n"
        }

  - name: "upcoming"
    label: "Restaurants à venir"
    folder: "_upcoming"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { 
          label: "Type de restaurant",
          name: "restaurant_type",
          widget: "select",
          options: [
            "Café-Boulangerie",
            "Bistro-Gastronomique",
            "Végétalien",
            "Mexicain",
            "Steakhouse",
            "Libanais",
            "Pub & Grill",
            "Marocain",
            "Italien",
            "Asiatique",
            "Bistro",
            "Américain",
            "Fusion",
            "Méditerranéen",
            "Fast-food",
            "Fruits de mer",
            "Autre"
          ],
          hint: "Sélectionnez le type de cuisine"
        }
      - {
          label: "Nom du restaurant",
          name: "title",
          widget: "string",
          hint: "Nom du restaurant"
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          hint: "Une brève description du restaurant (max 150 caractères)",
          pattern: ['.{0,150}', "Maximum 150 caractères"]
        }
      - {
          label: "Adresse",
          name: "location",
          widget: "string",
          hint: "Adresse du restaurant",
          required: false
        }
      - {
          label: "Ordre d'affichage",
          name: "order",
          widget: "number",
          value_type: "int",
          min: 1,
          default: 50,
          hint: "Position dans la liste (1 = premier)"
        }
